<script setup lang="ts">
const { unix } = defineProps<{
  unix: number;
}>();
</script>

<template>
  <footer class="app-footer">
    <span class="app-footer__text">
      Code coverage generated by
      <a
        href="https://github.com/akcyp/coverage-pretty-html-reporter"
        target="_blank"
        rel="noreferrer"
        class="app-footer__link"
      >
        coverage-pretty-html-reporter
      </a>
      at {{ new Date(unix).toLocaleString() }}
    </span>
  </footer>
</template>

<style scoped>
.app-footer {
  height: 22px;
  padding: 0 12px;
  display: flex;
  align-items: center;
  justify-content: flex-end;
  background-color: #191919;
  color: #d4d4d4;
  font-size: 11px;
  border-top: 1px solid #333333;
}

.app-footer__text {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.app-footer__link {
  color: #d4d4d4;
  text-decoration: none;
}

.app-footer__link:hover {
  text-decoration: underline;
  color: #ffffff;
}
</style>
