<script setup lang="ts">
  const { unix } = defineProps<{
    unix: number;
  }>()
</script>
<template>
  <footer text-xs mt="16px" text-center>
    Code coverage generated by <a href="https://github.com/akcyp/coverage-pretty-html-reporter" target="_blank" c="blue">coverage-pretty-html-reporter</a> at {{ new Date(unix).toLocaleString() }}
  </footer>
</template>
