<script setup lang="ts">
  const date = defineProps<{
    date: Date;
  }>()
</script>
<template>
  <footer text-xs mt="16px" text-center>
    Code coverage generated by <span c="blue">istanbul-pretty-html-reporter</span> at {{ date.toLocaleString() }}
  </footer>
</template>
