<script setup lang="ts">

</script>

<template>
  <div h-screen w-screen overflow="hidden" p="4" flex flex-col>
    <nav text-md pb-2>
      <span>All files</span>
      <span mx-1>/</span>
      <span>library</span>
      <span mx-1>/</span>
      <span>core</span>
    </nav>

    <main p-2 flex flex-col flex-justify-between text-sm>
      <div>Statements: 0% (0/20)</div>
      <div>Branches: 0% (0/20)</div>
      <div>Functions: 0% (0/20)</div>
      <div>Lines: 0% (0/20)</div>
    </main>

    <section w="100%" h="60%">
      <table w="100%" h-1>
        <thead>
          <th>File</th>
          <th></th>
          <th>Statements</th>
          <th>Branches</th>
          <th>Functions</th>
          <th>Lines</th>
        </thead>
        <tbody>
          <tr p="x-2 y-1" border-rounded cursor-pointer hover="bg-active">
            <td text-sm truncate font-light p-1>Point.spec.ts</td>
            <td p-2 w-50>
              <div b-1 w="100%" h="100%">
                <div w="30%" h="100%" bg="green-500"></div>
              </div>
            </td>
            <td text-sm p-1 text-center>0% (0/20)</td>
            <td text-sm p-1 text-center>0% (0/20)</td>
            <td text-sm p-1 text-center>0% (0/20)</td>
            <td text-sm p-1 text-center>0% (0/20)</td>
          </tr>
          <tr p="x-2 y-1" border-rounded cursor-pointer hover="bg-active">
            <td text-sm truncate font-light p-1>Point.spec.ts</td>
            <td p-2 w-50>
              <div b-1 w="100%" h="100%">
                <div w="30%" h="100%" bg="green-500"></div>
              </div>
            </td>
            <td text-sm p-1 text-center>0% (0/20)</td>
            <td text-sm p-1 text-center>0% (0/20)</td>
            <td text-sm p-1 text-center>0% (0/20)</td>
            <td text-sm p-1 text-center>0% (0/20)</td>
          </tr>
        </tbody>
      </table>
    </section>

    <footer text-xs mt="auto" text-center>
      Code coverage generated by <span c="blue">istanbul-pretty-html-reporter</span> at {{ new Date().toLocaleString() }}
    </footer>
  </div>
</template>